-- CreateTable
CREATE TABLE "Autopart_Manufacturer" (
    "MANU_ID" TEXT NOT NULL,
    "MANU_NAME" TEXT NOT NULL,
    "MANU_COUNTRY" TEXT NOT NULL,
    "MANU_CATEGORY" TEXT NOT NULL,
    "MANU_ABBREVIATION" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "Autopart_Category" (
    "CATE_CODE" TEXT NOT NULL,
    "CATE_NAME" TEXT NOT NULL,
    "CATE_DESCRIPTION" TEXT
);

-- CreateTable
CREATE TABLE "Autopart" (
    "PART_ID" SERIAL NOT NULL,
    "PART_NAME" TEXT NOT NULL,
    "PART_DESCRIPTION" TEXT,
    "PART_OEM" TEXT NOT NULL,
    "PART_WEIGHT" TEXT NOT NULL,
    "MANU_ID" TEXT NOT NULL,
    "CATE_CODE" TEXT NOT NULL,

    CONSTRAINT "Autopart_pkey" PRIMARY KEY ("PART_ID")
);

-- CreateTable
CREATE TABLE "Model" (
    "MODEL_ID" SERIAL NOT NULL,
    "MODEL_NAME" TEXT NOT NULL,
    "MODEL_MAKE" TEXT NOT NULL,

    CONSTRAINT "Model_pkey" PRIMARY KEY ("MODEL_ID")
);

-- CreateTable
CREATE TABLE "Autopart_Model" (
    "MODE_NAME" TEXT NOT NULL,
    "PART_ID" INTEGER NOT NULL,
    "PART_OEM" TEXT NOT NULL,
    "MODE_YEARS" INTEGER NOT NULL,
    "MODE_MAKE" TEXT NOT NULL,

    CONSTRAINT "Autopart_Model_pkey" PRIMARY KEY ("PART_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "Autopart_Manufacturer_MANU_ID_key" ON "Autopart_Manufacturer"("MANU_ID");

-- CreateIndex
CREATE UNIQUE INDEX "Autopart_Category_CATE_CODE_key" ON "Autopart_Category"("CATE_CODE");

-- CreateIndex
CREATE UNIQUE INDEX "Model_MODEL_NAME_MODEL_MAKE_key" ON "Model"("MODEL_NAME", "MODEL_MAKE");

-- AddForeignKey
ALTER TABLE "Autopart" ADD CONSTRAINT "Autopart_MANU_ID_fkey" FOREIGN KEY ("MANU_ID") REFERENCES "Autopart_Manufacturer"("MANU_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Autopart" ADD CONSTRAINT "Autopart_CATE_CODE_fkey" FOREIGN KEY ("CATE_CODE") REFERENCES "Autopart_Category"("CATE_CODE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Autopart_Model" ADD CONSTRAINT "Autopart_Model_PART_ID_fkey" FOREIGN KEY ("PART_ID") REFERENCES "Autopart"("PART_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Autopart_Model" ADD CONSTRAINT "Autopart_Model_MODE_NAME_MODE_MAKE_fkey" FOREIGN KEY ("MODE_NAME", "MODE_MAKE") REFERENCES "Model"("MODEL_NAME", "MODEL_MAKE") ON DELETE RESTRICT ON UPDATE CASCADE;
